name: nodejs

on:
  push:
    branches: [ "0.1.x" ]
  pull_request:
    branches: [ "0.1.x" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.14
      uses: actions/setup-node@v3
      with:
        node-version: 18.14
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test

    # 👇 Store the dist folder
    - uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: dist
